# Production override for docker-compose
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  backend:
    build:
      target: production
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    volumes: []  # No source code mounting in production
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  redis:
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  postgres:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # Include nginx in production
  nginx:
    profiles: []  # Remove profile to include in default services